name: reviewdog
on: [pull_request]

jobs:
  analysis:
    name: complexity analysis
    runs-on: ubuntu-latest
    steps:
      - name: golang set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout
        uses: actions/checkout@v2
      - name: install complexity
        run: go get github.com/shoooooman/go-static-analysis/cmd/complexity
      - name: reviewdog set up
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: calc complexities with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            go vet -vettool=$(which complexity) ./... | \ 
            reviewdog -emf="%f:%l:%c:%m"  -reporter=github-pr-check -level=info
